### ISSUE TITLE
Support done/false error calls

### ISSUE THREAD

**Issue by PanierAvide** [GuillaumeAmat/osmose-request#1]
Hello Guillaume (happy new year !),
I will start to use your library in order to integrate Osmose errors into a [new project I'm working on](https://framagit.org/Pic4Carto/Pic4Review/tree/develop). Do you think your library can support API calls which [updates an error status](http://wiki.openstreetmap.org/wiki/Osmose/api/0.2#error) (`/error/<ID>/done` and `/error/<ID>/false`) ? That would allow to let other Osmose users know that an error is fixed.
Thanks :-)

**Comment by GuillaumeAmat** [comment]
Happy new year too @PanierAvide! :)

Great to hear that you want to use the project! Its goal is definitely to get close to a full support of the Osmose API routes. So yeah, it has to support your proposal.

Can you consider to make a PR for that? I'm kinda swamped right now ^^ (cf. leaflet-nectarivore, osm-ui, mapcontrib.next, etc.).

**Comment by PanierAvide** [comment]
Closing this issue as it was integrated !
